# Generated by Django 2.2.8 on 2019-12-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymouscustomer',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='anonymouscustomer',
            name='phone',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
